version: 2

project_name: comai

before:
  hooks:
    - go mod tidy

builds:
  - id: binaries
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version }}
      - -X main.GitCommit={{.ShortCommit }}
      - -X main.BuildDate={{.Date }}
      - -X main.GitBranch={{.Branch }}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^Merge"
      - "^merge"

release:
  github:
    owner: JulienQNN
    name: comai
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"
