version: 2

project_name: comai

before:
  hooks:
    - go mod tidy
    - mkdir -p completions
    - sh -c 'for shell in bash zsh fish; do go run . completion $shell > completions/comai.$shell; done'

builds:
  - id: binaries
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.BuildDate={{.Date}}
      - -X main.GitBranch={{.Branch}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ if .Logins }} ({{ .Logins | englishJoin }}){{ end }}"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - typo
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

homebrew_casks:
  - name: comai
    repository:
      owner: JulienQNN
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/JulienQNN/comai"
    description: "Use AI to write your git commit messages and more"
    license: MIT
    completions:
      bash: "completions/comai.bash"
      zsh: "completions/comai.zsh"
      fish: "completions/comai.fish"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/comai"]
          end

winget:
  - name: comai
    repository:
      owner: JulienQNN
      name: winget-pkgs
      branch: main
      token: "{{ .Env.WINGET_GITHUB_TOKEN }}"
    publisher: JulienQNN
    package_identifier: "JulienQNN.comai"
    license: "MIT"
    publisher_url: "https://github.com/JulienQNN/comai"
    short_description: "Use AI to write your git commit messages and more"

nfpms:
  - id: packages
    package_name: comai
    vendor: JulienQNN
    maintainer: "JulienQNN"
    homepage: "https://github.com/JulienQNN/comai"
    description: "Use AI to write your git commit messages"
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
    contents:
      - src: completions/comai.bash
        dst: /usr/share/bash-completion/completions/comai
      - src: completions/comai.zsh
        dst: /usr/share/zsh/vendor-completions/_comai
      - src: completions/comai.fish
        dst: /usr/share/fish/vendor_completions.d/comai.fish
      - src: README.md
        dst: /usr/share/doc/comai/README.md
      - src: LICENSE
        dst: /usr/share/doc/comai/LICENSE

release:
  github:
    owner: JulienQNN
    name: comai
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"
